# Generated by Django 2.1.7 on 2019-02-20 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=15, verbose_name='Name to display')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Avatar')),
                ('biography', models.TextField(blank=True, default=None, verbose_name='Biography')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='Birthday')),
                ('location', models.CharField(blank=True, max_length=15, null=True, verbose_name='Location')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('followers', models.ManyToManyField(related_name='profile_following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(related_name='profile_followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
