# Generated by Django 2.1.7 on 2019-02-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190220_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Biography'),
        ),
    ]
