# Generated by Django 2.1.7 on 2019-02-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190227_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/placeholder.gif', upload_to='avatars', verbose_name='Avatar'),
        ),
    ]
