# Generated by Django 2.1.7 on 2019-02-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=280, verbose_name='Twist message')),
                ('created', models.DateField(auto_now=True)),
                ('likes', models.ManyToManyField(related_name='post_likes', to='accounts.Profile')),
                ('replies', models.ManyToManyField(to='posts.Post')),
                ('retwists', models.ManyToManyField(related_name='post_retwists', to='accounts.Profile')),
            ],
        ),
    ]
