# Generated by Django 2.1.7 on 2019-02-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190220_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='replies',
            field=models.ManyToManyField(blank=True, to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='retwists',
            field=models.ManyToManyField(blank=True, related_name='post_retwists', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='supports',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to='accounts.Profile'),
        ),
    ]
